#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck disable=SC2086
# shellcheck source=/dev/null
#
# Copyright (C) 2023-02 xealea <xealea@proton.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Number of download threads
THREADS=16

# Prompt the user to enter the download URL
read -p "Enter the download URL: " URL

# Exit if no URL is provided
if [ -z "$URL" ]; then
  echo "No download URL provided. Exiting."
  exit 1
fi

# Get the output file name from the download URL
OUTPUT=$(basename "$URL")

# Download the file with aria2c
aria2c -c -x "$THREADS" -o "$OUTPUT" "$URL"
