#!/bin/bash

# Number of download threads
THREADS=16

# Prompt the user to enter the download URL
read -p "Enter the download URL: " URL

# Exit if no URL is provided
if [ -z "$URL" ]; then
  echo "No download URL provided. Exiting."
  exit 1
fi

# Get the output file name from the download URL
OUTPUT=$(basename "$URL")

# Download the file with aria2c
aria2c -c -x "$THREADS" -o "$OUTPUT" "$URL"
