#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck disable=SC2086
# shellcheck source=/dev/null
#
# Copyright (C) 2023-02 xealea <xealea@proton.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

read -p "Enter your email address: " email

echo "Generating SSH key..."
ssh-keygen -t rsa -b 4096 -C "$email"
echo "SSH key generated."

echo "Copying SSH key to clipboard..."
xclip -sel clip < ~/.ssh/id_rsa.pub
echo "SSH key copied to clipboard."

echo "Opening GitHub settings page..."
xdg-open "https://github.com/settings/keys"
echo "Please add the SSH key to your GitHub account."
