#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck source=/dev/null
#
# Copyright (C) 2023-02 xealea <xealea@proton.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd /tmp/cirrus-ci-build/TMunch-Kernel || exit

# Anykernel3
git clone --depth=1 https://github.com/Tea-Droid/Anykernel3 anykernel

# Clone compiler
if [[ "$@" =~ "aosp-clang"* ]]; then
	git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86/ -b master --depth=1 gas
	git clone https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone/ -b 11 --depth=1 clang
elif [[ "$@" =~ "gcc"* ]]; then
	git clone https://github.com/mvaisakh/gcc-arm -b gcc-master --depth=1 gcc32
	git clone https://github.com/mvaisakh/gcc-arm64 -b gcc-master --depth=1 gcc64
else
	git clone https://github.com/kdrag0n/proton-clang -b master --depth=1 clang
fi
